apiVersion: v1
kind: ReplicationController
metadata:
  name: kuber-rc
spec:
  replicas: 3
  selector:
    app: https-server
  template:
    metadata:
      name: kuber-app
      labels:
        app: https-server
    spec:
      containers:
        - name: kuber-app-image
          image: nikolayv0212/kuber
          ports:
            - containerPort: 8000